// GENERATED BY uk.ipfreely.testing.c.GenerateCTests
#ifndef IPFREELY_TESTSTRUCTS_H
#define IPFREELY_TESTSTRUCTS_H

#include "../ip.h"

typedef struct tc
{
    const char *desc;
    const ipf_addr left;
    const ipf_addr right;
    const ipf_addr expected;
} testcase;

const int TEST_CASE_LEN = 4;

const testcase TESTS_V4_NOT[] = {
{
    .desc = "~96.180.32.187 = 159.75.223.68",
    .left = {
        .high = 0x0,
        .low = 0x60b420bb,
        .family = IPF_V4,
    },
    .right = {
        .high = 0x0,
        .low = 0x60b420bb,
        .family = IPF_V4,
    },
    .expected = {
        .high = 0x0,
        .low = 0x9f4bdf44,
        .family = IPF_V4,
    },
}, {
    .desc = "~96.180.32.187 = 159.75.223.68",
    .left = {
        .high = 0x0,
        .low = 0x60b420bb,
        .family = IPF_V4,
    },
    .right = {
        .high = 0x0,
        .low = 0x3851d9d4,
        .family = IPF_V4,
    },
    .expected = {
        .high = 0x0,
        .low = 0x9f4bdf44,
        .family = IPF_V4,
    },
}, {
    .desc = "~56.81.217.212 = 199.174.38.43",
    .left = {
        .high = 0x0,
        .low = 0x3851d9d4,
        .family = IPF_V4,
    },
    .right = {
        .high = 0x0,
        .low = 0x60b420bb,
        .family = IPF_V4,
    },
    .expected = {
        .high = 0x0,
        .low = 0xc7ae262b,
        .family = IPF_V4,
    },
}, {
    .desc = "~56.81.217.212 = 199.174.38.43",
    .left = {
        .high = 0x0,
        .low = 0x3851d9d4,
        .family = IPF_V4,
    },
    .right = {
        .high = 0x0,
        .low = 0x3851d9d4,
        .family = IPF_V4,
    },
    .expected = {
        .high = 0x0,
        .low = 0xc7ae262b,
        .family = IPF_V4,
    },
}};

const testcase TESTS_V6_NOT[] = {
{
    .desc = "~60b4:20bb:3851:d9d4:7acb:933d:be70:399b = 9f4b:df44:c7ae:262b:8534:6cc2:418f:c664",
    .left = {
        .high = 0x60b420bb3851d9d4,
        .low = 0x7acb933dbe70399b,
        .family = IPF_V6,
    },
    .right = {
        .high = 0x60b420bb3851d9d4,
        .low = 0x7acb933dbe70399b,
        .family = IPF_V6,
    },
    .expected = {
        .high = 0x9f4bdf44c7ae262b,
        .low = 0x85346cc2418fc664,
        .family = IPF_V6,
    },
}, {
    .desc = "~60b4:20bb:3851:d9d4:7acb:933d:be70:399b = 9f4b:df44:c7ae:262b:8534:6cc2:418f:c664",
    .left = {
        .high = 0x60b420bb3851d9d4,
        .low = 0x7acb933dbe70399b,
        .family = IPF_V6,
    },
    .right = {
        .high = 0xf6c92da33af01d4f,
        .low = 0xb770e98c0325f41d,
        .family = IPF_V6,
    },
    .expected = {
        .high = 0x9f4bdf44c7ae262b,
        .low = 0x85346cc2418fc664,
        .family = IPF_V6,
    },
}, {
    .desc = "~f6c9:2da3:3af0:1d4f:b770:e98c:325:f41d = 936:d25c:c50f:e2b0:488f:1673:fcda:be2",
    .left = {
        .high = 0xf6c92da33af01d4f,
        .low = 0xb770e98c0325f41d,
        .family = IPF_V6,
    },
    .right = {
        .high = 0x60b420bb3851d9d4,
        .low = 0x7acb933dbe70399b,
        .family = IPF_V6,
    },
    .expected = {
        .high = 0x936d25cc50fe2b0,
        .low = 0x488f1673fcda0be2,
        .family = IPF_V6,
    },
}, {
    .desc = "~f6c9:2da3:3af0:1d4f:b770:e98c:325:f41d = 936:d25c:c50f:e2b0:488f:1673:fcda:be2",
    .left = {
        .high = 0xf6c92da33af01d4f,
        .low = 0xb770e98c0325f41d,
        .family = IPF_V6,
    },
    .right = {
        .high = 0xf6c92da33af01d4f,
        .low = 0xb770e98c0325f41d,
        .family = IPF_V6,
    },
    .expected = {
        .high = 0x936d25cc50fe2b0,
        .low = 0x488f1673fcda0be2,
        .family = IPF_V6,
    },
}};
#endif
