package uk.ipfreely.testing.c;

import uk.ipfreely.Addr;
import uk.ipfreely.Family;
import uk.ipfreely.V4;
import uk.ipfreely.V6;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.function.BiFunction;

/**
 * Generates some expectations for C implementation.
 */
public class GenerateCTests {
    private static final List<V4> S4 = sample(Family.v4());
    private static final List<V6> S6 = sample(Family.v6());

    public static void main(String[] args) throws IOException {
        var prefix = """
                #ifndef IPFREELY_TESTSTRUCTS_H
                #define IPFREELY_TESTSTRUCTS_H
                
                #include "../ip.h"
                
                typedef struct ips
                {
                    const ipf_addr left;
                    const ipf_addr right;
                } inputs;
                
                typedef struct tc
                {
                    const char *desc;
                    const ipf_addr expected;
                } testcase;
                """;
        var suffix = "#endif\n";

        try (var out = Files.newBufferedWriter(Path.of("teststructs.h"))) {
            out.append("// GENERATED BY ").append(GenerateCTests.class.getName()).append("\n");
            out.append(prefix);

            var inputs = inputs();

            var size = String.valueOf(inputs.size());
            out.append("\nconst int TEST_CASE_LEN = ").append(size).append(";\n");

            writeInputArray(inputs, out);

            var t = new TreeMap<String, List<Expectations>>();
            expectations("NOT", S4, (l, r) -> l.not(), (a, b, c) -> "~" + a + " = " + c, t);
            expectations("NOT", S6, (l, r) -> l.not(), (a, b, c) -> "~" + a + " = " + c, t);

            expectations("AND", S4, Addr::and, (a, b, c) -> a + " & " + b + " = " + c, t);
            expectations("AND", S6, Addr::and, (a, b, c) -> a + " & " + b + " = " + c, t);

            expectations("OR", S4, Addr::or, (a, b, c) -> a + " | " + b + " = " + c, t);
            expectations("OR", S6, Addr::or, (a, b, c) -> a + " | " + b + " = " + c, t);

            expectations("XOR", S4, Addr::xor, (a, b, c) -> a + " ^ " + b + " = " + c, t);
            expectations("XOR", S6, Addr::xor, (a, b, c) -> a + " ^ " + b + " = " + c, t);

            expectations("ADD", S4, Addr::add, (a, b, c) -> a + " + " + b + " = " + c, t);
            expectations("ADD", S6, Addr::add, (a, b, c) -> a + " + " + b + " = " + c, t);

            expectations("SUB", S4, Addr::subtract, (a, b, c) -> a + " - " + b + " = " + c, t);
            expectations("SUB", S6, Addr::subtract, (a, b, c) -> a + " - " + b + " = " + c, t);

            expectations("MUL", S4, Addr::multiply, (a, b, c) -> a + " * " + b + " = " + c, t);
            expectations("MUL", S6, Addr::multiply, (a, b, c) -> a + " * " + b + " = " + c, t);

            expectations("DIV", S4, Addr::divide, (a, b, c) -> a + " / " + b + " = " + c, t);
            expectations("DIV", S6, Addr::divide, (a, b, c) -> a + " / " + b + " = " + c, t);

            expectations("MOD", S4, Addr::subtract, (a, b, c) -> a + " % " + b + " = " + c, t);
            expectations("MOD", S6, Addr::subtract, (a, b, c) -> a + " % " + b + " = " + c, t);

            writeExpectationArrays(t, out);

            out.append(suffix);
        }
    }

    private static void writeInputArray(List<Inputs> inputs, Appendable out) throws IOException {
        var template = """
        {
            .left = %s,
            .right = %s,
        }""";

        out.append("\nconst inputs TEST_CASE_INPUTS[] = {\n");
        var delim = "";
        for (var i : inputs) {
            var e = String.format(template, i.left, i.right);
            out.append(delim);
            delim = ", ";
            out.append(e);
        }
        out.append("\n};\n");
    }

    private static void writeExpectationArrays(Map<String, List<Expectations>> map, Appendable out) throws IOException {
        var template = """
        {
            .expected = %s,
            .desc = "%s",
        }""";

        for (var e : map.entrySet()) {
            out.append("\nconst testcase TEST_CASE_").append(e.getKey()).append("[] = {\n");
            var delim = "";
            for (var exp : e.getValue()) {
                out.append(delim);
                delim = ", ";
                var s = template.formatted(exp.answer, exp.description);
                out.append(s);
            }
            out.append("\n};\n");
        }
    }

    private static <A extends Addr<A>> String fmt(A address) {
        var high = Long.toUnsignedString(address.highBits(), 16);
        var low = Long.toUnsignedString(address.lowBits(), 16);
        var family = address.family() == Family.v4()
                ? "IPF_V4"
                : "IPF_V6";

        var template = """
        {
                .high = 0x%s,
                .low = 0x%s,
                .family = %s,
            }""";

        return String.format(template, high, low, family);
    }

    private static <A extends Addr<A>> void expectations(String name, List<A> addresses, BiFunction<A, A, A> result, Desc<A> desc, Map<String, List<Expectations>> target) {
        var list = target.computeIfAbsent(name, k -> new ArrayList<>());
        for (A left : addresses) {
            for (A right : addresses) {
                String description;
                String expected;
                try {
                    A e = result.apply(left, right);
                    expected = fmt(e);
                    description = desc.apply(left, right, e);
                } catch (ArithmeticException e) {
                    expected = fmt(right.family().min());
                    description = "invalid test case";
                }
                list.add(new Expectations(expected, description));
            }
        }
    }

    private static List<Inputs> inputs() {
        var result = inputs(S4);
        result.addAll(inputs(S6));
        return result;
    }

    private static <A extends Addr<A>> List<Inputs> inputs(List<A> addresses) {
        var result = new ArrayList<Inputs>();
        for (A left : addresses) {
            var l = fmt(left);
            for (A right : addresses) {
                var r = fmt(right);
                result.add(new Inputs(l, r));
            }
        }
        return result;
    }

    private static <A extends Addr<A>> List<A> sample(Family<A> f) {
        var list = new ArrayList<A>();
        for (int i = 0; i < 9; i++) {
            list.add(f.parse(i));
        }
        list.add(f.max());
        list.add(f.max().shift(f.width() / 2));
        list.add(f.max().shift(-(f.width() / 2)));

        var ran = new Random(0);
        byte[] buf = new byte[f.width() / 8];
        for (int i = 0; i < 10; i++) {
            ran.nextBytes(buf);
            list.add(f.parse(buf));
        }

        return List.copyOf(list);
    }

    @FunctionalInterface
    private interface Desc<A extends Addr<A>> {
        String apply(A left, A right, A expected);
    }

    private record Inputs(String left, String right) {
    }

    private record Expectations(String answer, String description) {
    }
}
