package uk.ipfreely.testing.c;

import uk.ipfreely.Addr;
import uk.ipfreely.Family;
import uk.ipfreely.testing.Addresses;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Random;
import java.util.function.BiFunction;

/**
 * Generates some expectations for C implementation.
 */
public class GenerateCTests {

    public static void main(String[] args) throws IOException {
        var prefix = """
                #ifndef IPFREELY_TESTSTRUCTS_H
                #define IPFREELY_TESTSTRUCTS_H
                
                #include "../ip.h"
                
                typedef struct tc
                {
                    const char *desc;
                    const ipf_addr left;
                    const ipf_addr right;
                    const ipf_addr expected;
                } testcase;
                """;
        var suffix = "#endif\n";

        try (var out = Files.newBufferedWriter(Path.of("teststructs.h"))) {
            out.append("// GENERATED BY ").append(GenerateCTests.class.getName()).append("\n");
            out.append(prefix);

            int n = sample(Family.v4()).size();
            var size = String.valueOf(n * n);
            out.append("\nconst int TEST_CASE_LEN = ").append(size).append(";\n");

            operations(Family.v4(), out);
            operations(Family.v6(), out);
            out.append(suffix);
        }
    }

    private static <A extends Addr<A>> void operations(Family<A> f, Appendable out) throws IOException {
        var addrs = sample(f);
        String prefix = f == Family.v4() ? "TESTS_V4_" : "TESTS_V6_";
        // bitwise
        operator(prefix + "NOT", addrs, (l, r) -> l.not(), (a, b, c) -> "~" + a + " = " + c, out);
//        operator(prefix + "AND", addrs, Addr::and, (a, b, c) -> a + " & " + b + " = " + c, out);
//        operator(prefix + "OR", addrs, Addr::or, (a, b, c) -> a + " | " + b + " = " + c, out);
//        operator(prefix + "XOR", addrs, Addr::xor, (a, b, c) -> a + " ^ " + b + " = " + c, out);
//        // arithmetic
//        operator(prefix + "ADD", addrs, Addr::add, (a, b, c) -> a + " + " + b + " = " + c, out);
//        operator(prefix + "SUB", addrs, Addr::subtract, (a, b, c) -> a + " - " + b + " = " + c, out);
//        operator(prefix + "MUL", addrs, Addr::multiply, (a, b, c) -> a + " * " + b + " = " + c, out);
//        operator(prefix + "DIV", addrs, Addr::divide, (a, b, c) -> a + " / " + b + " = " + c, out);
//        operator(prefix + "MOD", addrs, Addr::subtract, (a, b, c) -> a + " % " + b + " = " + c, out);
    }

    private static <A extends Addr<A>> void operator(String name, Collection<A> addrs, BiFunction<A, A, A> result, Desc<A> desc, Appendable out) throws IOException {
        out.append("\nconst testcase ").append(name).append("[] = {\n");
        var delim = "";
        for (A l : addrs) {
            for (A r : addrs) {
                try {
                    var e = element(result, l, r, desc);

                    out.append(delim);
                    delim = ", ";
                    out.append(e);
                } catch (ArithmeticException e) {
                    // divide by zero
                }
            }
        }
        out.append("};\n");
    }

    private static <A extends Addr<A>> String element(BiFunction<A, A, A> result, A left, A right, Desc<A> desc) {
        A expected = result.apply(left, right);
        var d = desc.apply(left, right, expected);

        var l = fmt(left);
        var r = fmt(right);
        var e = fmt(expected);

        var template = """
        {
            .desc = "%s",
            .left = %s,
            .right = %s,
            .expected = %s,
        }""";

        return String.format(template, d, l, r, e);
    }

    private static <A extends Addr<A>> String fmt(A address) {
        var high = Long.toUnsignedString(address.highBits(), 16);
        var low = Long.toUnsignedString(address.lowBits(), 16);
        var family = address.family() == Family.v4()
                ? "IPF_V4"
                : "IPF_V6";

        var template = """
        {
                .high = 0x%s,
                .low = 0x%s,
                .family = %s,
            }""";

        return String.format(template, high, low, family);
    }

    private static <A extends Addr<A>> Collection<A> sample(Family<A> f) {
        var list = new ArrayList<A>();
//        for (int i = 0; i < 10; i++) {
//            list.add(f.parse(i));
//        }
//        list.add(f.max());
//        list.add(f.max().shift(f.width() / 2));
//        list.add(f.max().shift(-(f.width() / 2)));

        var ran = new Random(0);
        byte[] buf = new byte[f.width() / 8];
        for (int i = 0; i < 2; i++) {
            ran.nextBytes(buf);
            list.add(f.parse(buf));
        }

        return list;
    }

    @FunctionalInterface
    private interface Desc<A extends Addr<A>> {
        String apply(A left, A right, A expected);
    }
}
